<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Stripe, Mailgun, Mandrill, and others. This file provides a sane
    | default location for this type of information, allowing packages
    | to have a conventional place to find your various credentials.
    |
    */

    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
        'endpoint' => env('MAILGUN_ENDPOINT', 'api.mailgun.net'),
    ],

    'mandrill' => [
        'secret' => env('MANDRILL_SECRET'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'stripe' => [
        'model'  => App\User::class,
        'key'    => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],

    'google' => [
        'maps_api_key' => env('GOOGLE_MAPS_API'),
    ],

    'microsoft' => [
        'tenant_id' => env('MICROSOFT_TENANT_ID'),
        'client_id' => env('MICROSOFT_CLIENT_ID'),
        'client_secret' => env('MICROSOFT_CLIENT_SECRET'),
    ],

    'jamf' => [
        'url' => env('JAMF_URL'), // e.g., https://yourcompany.jamfcloud.com
        'username' => env('JAMF_USERNAME'),
        'password' => env('JAMF_PASSWORD'),
    ],

    'huntress' => [
        'url' => env('HUNTRESS_API_URL', 'https://api.huntress.io'),
        'api_key' => env('HUNTRESS_API_KEY'),
        'timeout' => env('HUNTRESS_API_TIMEOUT', 15),
        'chunk_size' => env('HUNTRESS_SYNC_CHUNK_SIZE', 100),
        'incident_limit' => env('HUNTRESS_INCIDENT_LIMIT', 3),
        'remediation_limit' => env('HUNTRESS_REMEDIATION_LIMIT', 3),
    ],

    'snipeit' => [
        'url' => env('SNIPEIT_URL'), // e.g., https://your-snipeit.com
        'api_token' => env('SNIPEIT_API_TOKEN'),
    ]

];
